
import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {
 
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>  
      <main className="flex items-center justify-center">
        
      
      </main>
    </>
  );
};

export default Home;
